// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using PlogBot.Data;
using PlogBot.Data.Enums;
using System;

namespace PlogBot.Data.Migrations
{
    [DbContext(typeof(PlogDbContext))]
    [Migration("20180427054712_AddImageUrlToClanMember")]
    partial class AddImageUrlToClanMember
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("PlogBot.Data.Entities.ClanMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<int>("Class");

                    b.Property<DateTime>("Created");

                    b.Property<ulong?>("DiscordId");

                    b.Property<string>("ImageUrl");

                    b.Property<Guid?>("MainId");

                    b.Property<DateTime?>("Modified");

                    b.Property<string>("Name");

                    b.Property<string>("RealName");

                    b.HasKey("Id");

                    b.HasIndex("MainId");

                    b.ToTable("Plogs");
                });

            modelBuilder.Entity("PlogBot.Data.Entities.ClanMemberStatLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Accuracy");

                    b.Property<int>("AdditionalDamage");

                    b.Property<int>("AttackPower");

                    b.Property<int>("Block");

                    b.Property<int>("BossAttackPower");

                    b.Property<int>("BossDefense");

                    b.Property<Guid>("ClanMemberId");

                    b.Property<int>("Concentration");

                    b.Property<int>("Critical");

                    b.Property<int>("CriticalDamage");

                    b.Property<int>("CriticalDefense");

                    b.Property<int>("DamageReduction");

                    b.Property<int>("DebuffDamage");

                    b.Property<int>("DebuffDefense");

                    b.Property<int>("Defense");

                    b.Property<int>("EarthDamage");

                    b.Property<int>("Evasion");

                    b.Property<int>("FlameDamage");

                    b.Property<int>("FrostDamage");

                    b.Property<int>("Health");

                    b.Property<int>("HealthRegen");

                    b.Property<int>("HealthRegenCombat");

                    b.Property<int>("HongmoonLevel");

                    b.Property<int>("Level");

                    b.Property<int>("LightningDamage");

                    b.Property<int>("Piercing");

                    b.Property<int>("PvpAttackPower");

                    b.Property<int>("PvpDefense");

                    b.Property<DateTime>("Recorded");

                    b.Property<int>("ShadowDamage");

                    b.Property<int>("WindDamage");

                    b.HasKey("Id");

                    b.HasIndex("ClanMemberId");

                    b.HasIndex("Recorded");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("PlogBot.Data.Entities.ClanMember", b =>
                {
                    b.HasOne("PlogBot.Data.Entities.ClanMember", "Main")
                        .WithMany()
                        .HasForeignKey("MainId");
                });

            modelBuilder.Entity("PlogBot.Data.Entities.ClanMemberStatLog", b =>
                {
                    b.HasOne("PlogBot.Data.Entities.ClanMember", "ClanMember")
                        .WithMany("ClanMemberStatLogs")
                        .HasForeignKey("ClanMemberId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
